server:
  port: 8080
  servlet:
    contextPath: /api
spring:
  messages:
    basename: error-messages, parameter-name
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: redis
mybatis:
  mapper-locations: classpath*:/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: app.dao.handler.CodeValueEnumTypeHandler
security:
  allowedMethods:
    - GET
    - POST
    - PUT
    - DELETE
  allowedHeaders:
    - API-Key
    - User-Type
