spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/app"
    username: user
    password: password
security:
  allowedOrigins:
    - "*"
  maskRequestHeaderNames: []
  v1APISessionEnable: false
  v2APISessionEnable: false
