spring:
  datasource:
    url: jdbc:mysql://localhost:3307/app
    username: user
    password: password
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
logging:
  level:
    root: INFO
    app:
      dao: DEBUG
security:
  allowedOrigins:
    - "*"
