server:
  port: 8080
  servlet:
    contextPath: /api
spring:
  messages:
    basename: error-messages, parameter-name
  datasource:
    url: "jdbc:mysql://localhost:3306/app"
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: app.dao.handler.CodeValueEnumTypeHandler
logging:
  level:
    root: INFO
security:
  apiKey: b7e59712-906a-1ab2-f606-d5e8c60b381b
  allowedOrigins:
    - "*"
  allowedMethods:
    - GET
    - POST
    - PUT
    - DELETE
  allowedHeaders:
    - API-Key
    - User-Type
  maskRequestHeaderNames:
    - Authorization
    - API-Key