spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/app"
    username: user
    password: password
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      username: admin
      password: password
security:
  allowedOrigins:
    - "*"
  maskRequestHeaderNames: []
  v1APISessionEnable: true
  v2APISessionEnable: true
