version: "3.8"
services:
  app-db:
    container_name: "app-db"
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    tty: true
  app-redis:
    container_name: "app-redis"
    command: ["redis-server", "/etc/redis/redis.conf"]
    build: ./redis
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/users.acl:/etc/redis/users.acl
      - ./redis/data:/data
    ports:
      - "6379:6379"
    tty: true
