version: "3.8"
services:
  mysql-app:
    container_name: "mysql-app"
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./mysql/app-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    tty: true
  mysql-test:
    container_name: "mysql-test"
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/initdb.d/001_init_database.sql:/docker-entrypoint-initdb.d/001_init_database.sql
      - ./mysql/initdb.d/101_create_table.sql:/docker-entrypoint-initdb.d/101_create_table.sql
      - ./mysql/conf.d/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./mysql/test-db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    tty: true
  redis:
    container_name: "redis-app"
    command: ["redis-server", "/etc/redis/redis.conf"]
    build: ./redis
    volumes:
      - ./redis/conf:/etc/redis
      - ./redis/data:/data
    ports:
      - "6379:6379"
    tty: true
