version: "3.8"
services:
  mysql:
    container_name: "mysql-app"
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    tty: true
  redis:
    container_name: "redis-app"
    command: ["redis-server", "/etc/redis/redis.conf"]
    build: ./redis
    volumes:
      - ./redis/conf:/etc/redis
      - ./redis/data:/data
    ports:
      - "6379:6379"
    tty: true
